kind: Deployment
apiVersion: apps/v1
metadata:
  name: gcr-to-registry-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcr-to-registry-webhook
  template:
    metadata:
      labels:
        app: gcr-to-registry-webhook
    spec:
      containers:
        - name: gcr-to-registry-webhook
          image: ghcr.io/abstractinfrastructure/k8s-gcr-quickfix:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls
              mountPath: "/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: k8s-gcr-quickfix-tls
---
kind: Service
apiVersion: v1
metadata:
  name: gcr-to-registry-webhook
  namespace: kube-system
spec:
  selector:
    app: gcr-to-registry-webhook
  ports:
    - port: 443
      targetPort: 8443
---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: gcr-to-registry-webhook
  namespace: kube-system
webhooks:
  - name: gcr-to-registry.webhook.dev
    clientConfig:
      caBundle: REPLACEME
      service:
        namespace: kube-system
        name: gcr-to-registry-webhook
        path: /mutate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]